apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gotk-components.yaml
  - gotk-sync.yaml
  - webhook-token.yaml
  - receiver-service.yaml
  - notification-receiver.yaml
  - test.yaml
